version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: mock-exam-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: "exit 0"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mock-exam-backend
    ports:
      - "4000:4000" 
    environment:
      MONGO_URI: mongodb://mongodb:27017/mock-exam-db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./keys:/usr/src/app/keys # Mount the keys directory into the container

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
